0dy553y/odyssey

frontend/src/routing/RouteWithRedirect.tsx

dumb mistake due to always mounting the Redirect component even if user isn't at that route

Fix redirect

---

frontend/package.json
frontend/src/components/challengeProgressChart/ChallengeProgressChart.scss
frontend/src/components/challengeProgressChart/ChallengeProgressChart.tsx
frontend/src/components/challengeProgressChart/index.tsx
frontend/src/pages/challenge/ChallengeDetailsPage.tsx
frontend/src/pages/challenge/UserChallengeStats.scss
frontend/src/pages/challenge/UserChallengeStats.tsx
frontend/src/types/date.ts
frontend/yarn.lock

@jialin7878 might have some merge conflicts with you cos I made some changes to the tabs (or rather, added the other tabs)
P.S. The tabs cannot be clicked unless the drawer is pulled open. Is this a desired behaviour?
TODO:
- integrate with backend

Add stats tab

---

frontend/package.json
frontend/src/App.tsx
frontend/src/pages/profile/ProfilePage.tsx
frontend/yarn.lock

Fix margins on desktop view

---

backend/app/controllers/challenges_controller.rb
backend/app/controllers/user_tasks_controller.rb
backend/config/routes.rb
frontend/src/api/challenges.ts
frontend/src/pages/challenge/ScheduleModal.tsx
frontend/src/store/challenges/operations.ts
frontend/src/types/challenges.ts

help to roast my code hehe thanks

[draft] join challenge

---

backend/app/views/user_tasks/tasks_for_day.json.jbuilder
frontend/src/components/home/UserTaskCard.tsx
frontend/src/types/usertasks.ts

I **majorly** overthought the implementation for this one

Color user task card

---

backend/db/seeds.rb

Fix challenge name in seeds

---

frontend/src/components/notifications/NotificationsListItem.tsx

In line with how dates are displayed in feed posts.
Fixes #134.

Fix notifications date display

---

deployment/nginx/sites-enabled/odyssey-app.com

Enable HTTPS for www subdomain

---

backend/app/controllers/user_challenges_controller.rb
backend/app/controllers/user_tasks_controller.rb
backend/app/views/user_challenges/all_user_challenges_for_challenge.jbuilder
backend/config/routes.rb
frontend/src/api/userchallenge.ts
frontend/src/components/challenge/ChallengeContent.tsx
frontend/src/components/common/ConfirmationModal.tsx
frontend/src/pages/challenge/ChallengeDetailsPage.tsx
frontend/src/store/userchallenges/operations.ts
frontend/src/store/userchallenges/selectors.ts
frontend/src/types/userchallenge.ts

Resolves https://github.com/0dy553y/odyssey/issues/111

Forfeit challenge

---

backend/app/views/challenges/show.json.jbuilder
frontend/src/components/challenge/ChallengeContent.tsx
frontend/src/types/challenges.ts

Resolves https://github.com/0dy553y/odyssey/issues/149

Add link to reference and display original creator

---

frontend/src/pages/badge/BadgePage.tsx
frontend/src/pages/completedChallenges/CompletedChallengesPage.tsx
frontend/src/pages/profile/ProfilePage.tsx
frontend/src/routing/routes.ts

- Fix bug where other profiles' completed challenges are not displayed
- Allow viewing of other profiles' badges

Viewing other profiles' completed challenges and badges

---

backend/lib/tasks/20211101013830_add_remaining_categories.rake
backend/lib/tasks/20211101101623_add_pull_up_music_production_and_squat.rake
frontend/src/components/challenge/ChallengeMilestones.tsx
frontend/src/components/feed/FeedPost.tsx

- Add pullup, music production and squat challenge 
- Display line break in task description

Add some seeds

---

frontend/src/components/challenge/ShareDialog.tsx
frontend/src/components/common/CopyTextField.tsx

Enforce proper separation of concerns for CopyTextField

---

frontend/src/components/category/CategoryHeader.scss
frontend/src/components/category/CategoryHeader.tsx

Sorry I realised the previous method also doesn't work as intended... this works for real now 👹

Fix category header positioning

---

backend/Gemfile.lock
frontend/src/components/map/composite/Island.tsx
frontend/src/components/map/mapTemplates/SpaceMap.tsx
frontend/src/components/map/mapTemplates/SpaceMapStructure.tsx

fixes #162 
also the map wasn't workin on prod, hope this fixes ?-?

more map fixes

---

backend/app/controllers/map_controller.rb
backend/app/views/map/friends_on_same_challenges.jbuilder
backend/app/views/user_challenges/all_completed_challenges.jbuilder
backend/db/migrate/20211102123038_add_prize_name_to_challenge.rb
backend/db/schema.rb
backend/db/seeds.rb
backend/lib/tasks/20211101130002_add_healthy_eating_social_media_detox_and_cs3216.rake
backend/lib/tasks/20211101153032_add_lego_mental_health_week_and_happiness.rake
frontend/src/components/badge/PrizeDisplay.tsx
frontend/src/components/badge/PrizeInfoModal.tsx
frontend/src/components/map/mapTemplates/SpaceMap.tsx
frontend/src/pages/badge/BadgePage.tsx
frontend/src/types/challenges.ts
frontend/src/types/prize.ts
frontend/src/types/userchallenge.ts
frontend/src/utils/prizes.ts

To be run on production once this is deployed:
```ruby
Challenge.find_by(name: 'Walking More').update(prize_name: 'Talaria')
Challenge.find_by(name: 'Gratitude Journaling').update(prize_name: 'Journal')
Challenge.find_by(name: 'Healthy Eating').update(prize_name: 'Moon Cheese')
Challenge.find_by(name: 'Social Media Detox').update(prize_name: 'Brick Phone')
Challenge.find_by(name: 'CS3216').update(prize_name: 'CS3216')
Challenge.find_by(name: 'LEGO').update(prize_name: 'LEGO')
```

Remove hardcoding of prizes

---

frontend/src/components/challenge/ChallengeContent.tsx
frontend/src/components/challenge/ScheduleModal.tsx

Fixes #175 
Also prevent user from joining more than 3 challenges
seems like server might have looped forever if any of our uses submitted empty schedule :0
ooh if i stay up 2 more hours i'll be able to catch seb

Fix bug of empty recurring schedule

---

backend/app/controllers/challenges_controller.rb
backend/app/controllers/posts_controller.rb
backend/config/routes.rb
frontend/src/api/posts.ts
frontend/src/components/challenge/ChallengeContent.tsx
frontend/src/pages/posts/PostsPage.tsx
frontend/src/pages/profile/ProfilePage.tsx
frontend/src/routing/routes.ts
frontend/src/store/posts/actions.ts
frontend/src/store/posts/operations.ts
frontend/src/store/posts/reducer.ts
frontend/src/store/posts/selectors.ts
frontend/src/store/posts/types.ts

Resolves https://github.com/0dy553y/odyssey/issues/154

Show posts by user in profile

---

frontend/src/App.tsx
frontend/src/components/category/CategoryListItem.tsx
frontend/src/components/challenge/ChallengeContent.tsx
frontend/src/components/explore/CategoryPreview.tsx
frontend/src/components/profile/ChallengeSummaries.tsx
frontend/src/pages/category/CategoryPage.tsx
frontend/src/pages/challenge/ChallengeDetailsPage.tsx
frontend/src/pages/explore/ExplorePage.tsx
frontend/src/pages/home/HomePage.tsx
frontend/src/pages/loading/LoadingPage.tsx

Blue link that is removed:
Also, added LoadingPage (still the circular spinner tho) and replaced all Skeletons with it

Remove blue link

---

frontend/src/components/home/UserTaskCard.tsx

Make user task card description scroll

---

frontend/public/index.html
frontend/src/pages/login/LoginPage.tsx
frontend/src/pages/onboarding/OnboardingPage.tsx
frontend/src/pages/registration/RegistrationPage.tsx
frontend/src/routing/routes.ts

Resolves https://github.com/0dy553y/odyssey/issues/183
Resolves https://github.com/0dy553y/odyssey/issues/57
https://github.com/0dy553y/odyssey/issues/171
- Not sure if the fix in this PR solves the issue. Need to test on production since I can only replicate this issue on an actual mobile device

Random Fixes

---

frontend/package.json
frontend/src/App.scss
frontend/src/App.tsx
frontend/yarn.lock

https://github.com/0dy553y/odyssey/issues/171
Hopefully resolves said issue...
Will have to test this on an actual mobile device

Fix nav bar?

---

frontend/src/components/category/CategoryListItem.tsx
frontend/src/components/feed/FeedPost.tsx
frontend/src/utils/progress.ts

Resolves https://github.com/0dy553y/odyssey/issues/217 
Resolves https://github.com/0dy553y/odyssey/issues/220

Fix missing progress rings

---

backend/lib/tasks/20211106010305_replace_healthy_eating.rake

Rework Healthy Eating challenge

---

backend/app/views/users/_user.json.jbuilder

Fixes #234 , thanks for the catch

Fix viewing other profiles blank issue

---

backend/lib/tasks/20211105103312_add_growth_and_school_challenge.rake
backend/lib/tasks/20211105115844_add_productivity_challenge.rake

Update titles to follow capitalisation, modify description for Starting the Year Right

Small seed changes

---

frontend/src/pages/home/HomePage.tsx

Using the primary colour though instead of red. Should I use red instead?
Fixes #196.

Add badge to notifications icon

---

frontend/src/store/usertasks/reducer.ts
frontend/src/store/usertasks/selectors.ts

Resolves https://github.com/0dy553y/odyssey/issues/251
mutability bad, immutability good

Fix disappearing cards

---

frontend/src/components/challenge/ScheduleModal.tsx
frontend/src/components/challenge/UserChallengeStats.scss
frontend/src/pages/onboarding/OnboardingPage.tsx
frontend/src/pages/profile/ProfilePage.tsx

Resolves https://github.com/0dy553y/odyssey/issues/254
Resolves https://github.com/0dy553y/odyssey/issues/237
Also, set all overflows to auto (which will hide the scrollbar if it isn't necessary)

Reposition edit profile menu anchor and remove unnecessary scrollbars

---

frontend/src/components/map/mapTemplates/SpaceMap.tsx

Fix blank map

---

frontend/src/components/notifications/NotificationsListItem.tsx

Some notification styling

---

backend/app/views/friend_requests/index.json.jbuilder
frontend/src/components/common/CharacterDisplay.tsx
frontend/src/components/common/userAvatar/UserAvatar.tsx
frontend/src/components/feed/FeedPost.tsx
frontend/src/components/friendsList/AddFriendsListItem.tsx
frontend/src/components/friendsList/FriendsListItem.tsx
frontend/src/components/map/composite/Character.tsx
frontend/src/components/notifications/NotificationsListItem.tsx
frontend/src/components/profile/ProfileHeader.tsx
frontend/src/pages/editProfile/EditProfilePage.tsx
frontend/src/types/friendrequests.ts
frontend/src/types/friends.ts

Closes #225
https://user-images.githubusercontent.com/59867654/140622443-89673c08-834f-4dbe-aa91-460a4619ff41.mov

Set default avatar heads to be character heads

---

frontend/src/components/challenge/ChallengeLimitModal.tsx
frontend/src/components/profile/FriendControls.tsx
frontend/src/pages/challenge/ChallengeDetailsPage.tsx

Style cancel friend modal...
Add modal when challenge limit is reached and user tries to join another challenge, I think snackbar is a bit confusing

More modal tings

---

frontend/src/components/challenge/ChallengeContent.tsx
frontend/src/components/feed/CreatePostModal.tsx
frontend/src/components/profile/FriendControls.tsx
frontend/src/components/profile/ProfileHeader.tsx
frontend/src/pages/category/CategoryPage.tsx
frontend/src/pages/challenge/ChallengeDetailsPage.tsx
frontend/src/store/posts/actions.ts
frontend/src/store/posts/operations.ts
frontend/src/store/posts/reducer.ts

Fixes https://github.com/0dy553y/odyssey/issues/273 
Fixes https://github.com/0dy553y/odyssey/issues/222

Fix friends control alignment and add fab in community tab

---

frontend/src/components/map/MapDialog.tsx

Fix map bug

---

frontend/src/components/common/BottomNavigationBar.tsx
frontend/src/components/common/SideNavigationBar.tsx
frontend/src/components/landing/Section.tsx
frontend/src/pages/home/HomePage.tsx
frontend/src/pages/landing/LandingPage.tsx
frontend/src/pages/onboarding/OnboardingPage.tsx
frontend/src/store/auth/operations.ts

#281 
tinker around with navbar and icons
Hide onboarding modal for now

Landing page firefight

---

backend/lib/tasks/20211108105931_add_earth_and_swimming_challenges.rake

https://github.com/0dy553y/odyssey/issues/238

Add earth and swimming challenges

---

frontend/src/pages/challenge/ChallengeDetailsPage.tsx

Fixes https://github.com/0dy553y/odyssey/issues/264

Add share to menu in challenge detail page

---

frontend/src/App.tsx

Remove feedback overlay

---

backend/app/models/friend_request.rb

Fix https://github.com/0dy553y/odyssey/issues/301

Update sorting order of friend request

---

backend/lib/tasks/20211109191057_update_meditation_journaling_category.rake

The script has been run on production.

Set category for Meditation & Gratitude Journaling to Mindfulness

---

backend/lib/tasks/20211109204949_add_photography_film_challenges.rake

could only think of stuff in the Creativity category :(
https://github.com/0dy553y/odyssey/issues/238

Add film and photography seeds

---

backend/app/models/task.rb
backend/lib/tasks/20211106153120_update_maps_for_challenges.rake
backend/lib/tasks/20211110120142_add_spring_cleaning_challenge.rake

Also update the max length of task names to be 55 characters.

Add Spring Cleaning challenge

---

backend/lib/tasks/20211110124501_add_abs_and_focus_and_love_challenge.rake

Add abs, focus, and love challenges

---

frontend/src/components/feed/FeedPostList.tsx
frontend/src/pages/challenge/ChallengeDetailsPage.tsx

As reported by Weiming in telegram chat

Fix overlapping Create Post fab in Challenge Details Page (Community tab)

---

frontend/src/pages/friends/AddFriendsPage.tsx

Resolves https://github.com/0dy553y/odyssey/issues/330

Exclude self in add friends list

---

backend/app/controllers/challenges_controller.rb

Resolves https://github.com/0dy553y/odyssey/issues/335

Exclude forfeited challenges in Create Post

---

backend/app/controllers/user_challenges_controller.rb
frontend/src/pages/editProfile/EditProfilePage.scss
frontend/src/pages/editProfile/EditProfilePage.tsx
frontend/src/store/userchallenges/operations.ts

Status message for forfeit challenge
Style edit profile page a bit
Add confirm discard changes modal if there were changes in the form (#302)

Confirm discard modal and other shenanigans

---

frontend/src/components/challenge/ChallengeMilestones.tsx
frontend/src/components/home/UserTaskCard.tsx
frontend/src/store/usertasks/operations.ts

Allow undo on cdp

---

frontend/src/pages/feed/FeedPage.tsx
frontend/src/store/posts/operations.ts
frontend/src/utils/constants.ts

Display loading instead of no posts yet

---

frontend/src/components/challengeProgressChart/ChallengeProgressChart.tsx

Buggy progress chart can be seen at https://odyssey-app.com/challenge/10 when you log in as `sebastian` (or when you have a task meant for an earlier date that is completed after a later task)

Fix buggy progress chart
